import type { ExamBoard } from "@/types";

/**
 * Tap-to-start curricula for onboarding: picking a curriculum then a subject
 * is enough for the planner to generate a session — no upload required.
 */
export interface CurriculumPreset {
  board: ExamBoard;
  label: string;
  subjects: string[];
}

/**
 * Syllabus units per `${board}:${subject}`, used for a narrower, multi-select
 * unit step after picking a subject (e.g. "Math AA" alone is far too broad).
 * Subjects without an entry skip the unit step.
 */
export const SUBJECT_UNITS: Record<string, string[]> = {
  "IB:Math AA": [
    "Number & Algebra",
    "Functions",
    "Geometry & Trigonometry",
    "Statistics & Probability",
    "Calculus",
  ],
  "IB:Math AI": [
    "Number & Algebra",
    "Functions & Modelling",
    "Geometry & Trigonometry",
    "Statistics & Probability",
    "Calculus",
  ],
  "IB:Physics": [
    "Space, Time & Motion",
    "Particulate Nature of Matter",
    "Wave Behaviour",
    "Fields",
    "Nuclear & Quantum Physics",
    "Energy & Thermodynamics",
  ],
  "IB:Chemistry": [
    "Structure: Models of Matter",
    "Structure: Bonding",
    "Reactivity: What Drives Reactions",
    "Reactivity: How Fast (Kinetics)",
    "Reactivity: Mechanisms",
    "Organic Chemistry",
  ],
  "IB:Biology": [
    "Unity & Diversity",
    "Form & Function",
    "Interaction & Interdependence",
    "Continuity & Change",
    "Cells & Molecular Biology",
    "Ecology",
  ],
  "IB:Economics": [
    "Microeconomics",
    "Macroeconomics",
    "The Global Economy",
    "Market Failure",
    "Development Economics",
  ],
  "IB:Business Management": [
    "Business Organisation",
    "Human Resources",
    "Finance & Accounts",
    "Marketing",
    "Operations Management",
  ],
  "IB:Psychology": [
    "Biological Approach",
    "Cognitive Approach",
    "Sociocultural Approach",
    "Research Methods",
    "Abnormal Psychology",
  ],
  "IB:History": [
    "Move to Global War",
    "Rights & Protest",
    "Authoritarian States",
    "Causes & Effects of Wars",
    "The Cold War",
  ],
  "IB:English A": [
    "Readers, Writers & Texts",
    "Time & Space",
    "Intertextuality",
    "Paper 1: Unseen Analysis",
    "Paper 2: Comparative Essay",
  ],
  "IB:Computer Science": [
    "System Fundamentals",
    "Computer Organisation",
    "Networks",
    "Computational Thinking & Programming",
    "Abstract Data Structures",
    "Databases",
  ],
  "IB:Environmental Systems": [
    "Foundations of ESS",
    "Ecosystems & Ecology",
    "Biodiversity & Conservation",
    "Water & Food Systems",
    "Atmosphere & Climate Change",
  ],
  "AP:Calculus AB": [
    "Limits & Continuity",
    "Differentiation",
    "Applications of Derivatives",
    "Integration",
    "Differential Equations",
    "Applications of Integrals",
  ],
  "AP:Calculus BC": [
    "Limits & Continuity",
    "Differentiation & Applications",
    "Integration & Applications",
    "Differential Equations",
    "Parametric, Polar & Vector Functions",
    "Infinite Series",
  ],
  "AP:Statistics": [
    "Exploring One-Variable Data",
    "Exploring Two-Variable Data",
    "Probability & Random Variables",
    "Sampling Distributions",
    "Inference: Means & Proportions",
    "Chi-Square & Regression Inference",
  ],
  "AP:Physics 1": [
    "Kinematics",
    "Dynamics (Forces)",
    "Circular Motion & Gravitation",
    "Energy",
    "Momentum",
    "Simple Harmonic Motion & Rotation",
  ],
  "AP:Chemistry": [
    "Atomic Structure & Properties",
    "Bonding & Intermolecular Forces",
    "Chemical Reactions & Stoichiometry",
    "Kinetics",
    "Thermodynamics",
    "Equilibrium, Acids & Bases",
  ],
  "AP:Biology": [
    "Chemistry of Life",
    "Cell Structure & Function",
    "Cellular Energetics",
    "Heredity & Gene Expression",
    "Natural Selection & Evolution",
    "Ecology",
  ],
  "AP:Psychology": [
    "Biological Bases of Behavior",
    "Cognition & Memory",
    "Development & Learning",
    "Social Psychology & Personality",
    "Mental & Physical Health",
  ],
  "AP:US History": [
    "Colonial America (1491–1754)",
    "Revolution & New Nation (1754–1800)",
    "Expansion & Civil War (1800–1877)",
    "Industrialization & Progressivism (1865–1945)",
    "Cold War America (1945–1980)",
    "Modern America (1980–present)",
  ],
  "AP:World History": [
    "The Global Tapestry (1200–1450)",
    "Networks of Exchange",
    "Land-Based & Maritime Empires",
    "Revolutions & Industrialization",
    "Global Conflict (1900–present)",
    "Globalization",
  ],
  "AP:Computer Science A": [
    "Primitive Types & Objects",
    "Boolean Expressions & Control Flow",
    "Iteration & Arrays",
    "Classes & Inheritance",
    "ArrayList & 2D Arrays",
    "Recursion & Sorting",
  ],
  "AP:English Language": [
    "Rhetorical Analysis",
    "Argument Essays",
    "Synthesis Essays",
    "Claims, Evidence & Reasoning",
    "Style & Rhetorical Choices",
  ],
  "AP:Microeconomics": [
    "Basic Economic Concepts",
    "Supply & Demand",
    "Production, Cost & Perfect Competition",
    "Imperfect Competition",
    "Factor Markets",
    "Market Failure & Government",
  ],
  "A_LEVEL:Maths": [
    "Algebra & Functions",
    "Coordinate Geometry & Trigonometry",
    "Calculus (Differentiation & Integration)",
    "Sequences & Series",
    "Statistics",
    "Mechanics",
  ],
  "A_LEVEL:Further Maths": [
    "Complex Numbers",
    "Matrices",
    "Further Calculus",
    "Further Vectors & Polar Coordinates",
    "Further Statistics",
    "Further Mechanics",
  ],
  "A_LEVEL:Physics": [
    "Mechanics & Materials",
    "Waves & Optics",
    "Electricity",
    "Fields (Gravitational, Electric, Magnetic)",
    "Nuclear & Particle Physics",
    "Thermal Physics",
  ],
  "A_LEVEL:Chemistry": [
    "Atomic Structure & Bonding",
    "Energetics & Kinetics",
    "Equilibria & Redox",
    "Inorganic Chemistry",
    "Organic Chemistry",
    "Analytical Techniques",
  ],
  "A_LEVEL:Biology": [
    "Biological Molecules",
    "Cells & Transport",
    "Genetics & Inheritance",
    "Energy Transfers (Respiration & Photosynthesis)",
    "Homeostasis & Response",
    "Ecosystems & Evolution",
  ],
  "A_LEVEL:Economics": [
    "Markets & Market Failure",
    "The National Economy",
    "Business Behaviour & Labour Markets",
    "The International Economy",
    "Fiscal & Monetary Policy",
  ],
  "A_LEVEL:Psychology": [
    "Social Influence",
    "Memory",
    "Attachment",
    "Psychopathology",
    "Approaches & Biopsychology",
    "Research Methods",
  ],
  "A_LEVEL:History": [
    "Tudors / Early Modern Britain",
    "Russia & the Soviet Union",
    "Germany 1871–1991",
    "The American Dream (USA 1945–80)",
    "Coursework / NEA Skills",
  ],
  "A_LEVEL:English Literature": [
    "Poetry Analysis",
    "Shakespeare",
    "Prose & the Novel",
    "Drama",
    "Unseen Texts & Comparison",
  ],
  "A_LEVEL:Computer Science": [
    "Programming & Algorithms",
    "Data Structures",
    "Computer Systems & Architecture",
    "Networks & Databases",
    "Theory of Computation",
  ],
  "GCSE:Maths": [
    "Number",
    "Algebra",
    "Ratio, Proportion & Rates of Change",
    "Geometry & Measures",
    "Probability & Statistics",
  ],
  "GCSE:Physics": [
    "Energy",
    "Electricity",
    "Particle Model of Matter",
    "Forces & Motion",
    "Waves",
    "Magnetism & Electromagnetism",
  ],
  "GCSE:Chemistry": [
    "Atomic Structure & the Periodic Table",
    "Bonding & Structure",
    "Quantitative Chemistry",
    "Chemical Changes & Energy",
    "Rates & Equilibrium",
    "Organic & Analysis",
  ],
  "GCSE:Biology": [
    "Cell Biology",
    "Organisation & Digestion",
    "Infection & Response",
    "Bioenergetics",
    "Homeostasis & Response",
    "Inheritance, Variation & Evolution",
  ],
  "GCSE:English": [
    "Reading Fiction (Paper 1)",
    "Reading Non-Fiction (Paper 2)",
    "Creative Writing",
    "Transactional Writing",
    "Poetry & Literature Texts",
  ],
  "GCSE:Geography": [
    "Natural Hazards",
    "Rivers & Coasts",
    "Urban Issues & Challenges",
    "The Changing Economic World",
    "Resource Management",
  ],
  "GCSE:History": [
    "Medicine Through Time",
    "Elizabethan England",
    "Weimar & Nazi Germany",
    "The Cold War",
    "Exam Skills & Source Analysis",
  ],
  "GCSE:Computer Science": [
    "Systems Architecture",
    "Memory & Storage",
    "Networks & Security",
    "Algorithms",
    "Programming Fundamentals",
  ],
  "SAT:Math": [
    "Algebra (Heart of Algebra)",
    "Problem Solving & Data Analysis",
    "Advanced Math (Passport)",
    "Geometry & Trigonometry",
  ],
  "SAT:Reading & Writing": [
    "Information & Ideas",
    "Craft & Structure",
    "Expression of Ideas",
    "Standard English Conventions",
  ],
};

export function unitsFor(board: ExamBoard, subject: string): string[] {
  return SUBJECT_UNITS[`${board}:${subject}`] ?? [];
}

export const CURRICULUM_PRESETS: CurriculumPreset[] = [
  {
    board: "IB",
    label: "IB",
    subjects: [
      "Math AA",
      "Math AI",
      "Physics",
      "Chemistry",
      "Biology",
      "Economics",
      "Business Management",
      "Psychology",
      "History",
      "English A",
      "Computer Science",
      "Environmental Systems",
    ],
  },
  {
    board: "AP",
    label: "AP",
    subjects: [
      "Calculus AB",
      "Calculus BC",
      "Statistics",
      "Physics 1",
      "Chemistry",
      "Biology",
      "Psychology",
      "US History",
      "World History",
      "Computer Science A",
      "English Language",
      "Microeconomics",
    ],
  },
  {
    board: "A_LEVEL",
    label: "A-Level",
    subjects: [
      "Maths",
      "Further Maths",
      "Physics",
      "Chemistry",
      "Biology",
      "Economics",
      "Psychology",
      "History",
      "English Literature",
      "Computer Science",
    ],
  },
  {
    board: "GCSE",
    label: "GCSE",
    subjects: [
      "Maths",
      "Physics",
      "Chemistry",
      "Biology",
      "English",
      "Geography",
      "History",
      "Computer Science",
    ],
  },
  {
    board: "SAT",
    label: "SAT",
    subjects: ["Math", "Reading & Writing"],
  },
];
